import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'

const font = Inter({ 
  subsets: ["latin"]
})

export const metadata = {
  title: 'Malagaco',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
