
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import LoginModal from './components/modals/LoginModal'
import RegisterModal from './components/modals/RegisterModal'
import RentModal from './components/modals/RentModal'
import { Toaster } from 'react-hot-toast'
import getCurrentUser from './actions/getCurrentUser'

const font = Inter({ 
  subsets: ["latin"]
})

export const metadata = {
  title: 'Malagaco',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster />
        <LoginModal />
        <RegisterModal />
        <RentModal />
        <Navbar 
          currentUser={currentUser}
        />
        {children}
      </body>
    </html>
  )
}
